// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI commands (migrate, db pull, studio) use DIRECT_URL, not DATABASE_URL:
  // the app's DATABASE_URL points at Supabase's transaction-mode pooler
  // (see src/lib/prisma.ts), which doesn't support the DDL/advisory-lock
  // behavior migrations need. Locally, both env vars point at the same
  // docker Postgres, so this has no effect in dev.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
